FROM ubuntu:22.04
RUN apt update -y
RUN apt -y install \
    net-tools \
    mysql-server \
    python3-pip \
    python3-venv \
    pkg-config \
    default-libmysqlclient-dev \
    nginx

EXPOSE 5000
EXPOSE 5001