name: Deploy MyAPP
run-name: ${{ github.actor }} is deploying MyAPP 🚀
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy-MyAPP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Config BackEnd file
        run: |
          sed -i 's/_USER_/${{ secrets.myapp_user }}/g' backend/myapi.py
          sed -i 's/_PASSWORD_/${{ secrets.myapp_passwd }}/g' backend/myapi.py
          sed -i 's/_HOST_/${{ secrets.terraform-20241009211840968000000001.cokirqnjz0cn.us-west-2.rds.amazonaws.com }}/g' backend/myapi.py
          sed -i 's/_DBNAME_/${{ secrets.myapp }}/g' backend/myapi.py

      - name: Deploy BackEnd
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.terraform-20241009211840968000000001.cokirqnjz0cn.us-west-2.rds.amazonaws.com}}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.CHAVE_SSH }}
          source: "backend/myapi.py"
          target: "/home/ubuntu/myapp/"
          strip_components: 1

      - name: Config FrontEnd file
        run: |
          sed -i 's/34.215.177.227/${{ secrets.HOST }}/g' frontend/index.html

      - name: Deploy FrontEnd
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: "frontend/index.html"
          target: "/var/www/html/"
          strip_components: 1
